# Generated by Django 4.2.1 on 2023-08-11 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('with_medicine_userapp', '0003_customuser_name_alter_customuser_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='phone_unmber',
            new_name='phone_number',
        ),
    ]
